### ISSUE TITLE
urllib from standard_library.install_aliases() not dealing correctly with unicode-strings

### ISSUE THREAD

**Issue by pkcakeout** [DIAGNijmegen/rse-gcapi#11]
See:

![image](https://user-images.githubusercontent.com/11632379/64055915-015b4a80-cb90-11e9-979f-303860aeb9f2.png)

The urljoin function that is imported this way fails to combine str and unicode strings in python2. A fix would be to unify the string types (`unicode(xxx)`), but this will hinder interoperability with python3. 

In order to not break python3, I will therefore undo urllib related the changes from commit 0d0e5ffa which attempted to implement a nicer way to import urljoin. The old code works for python2 and python3 as well without breaking on combining unicode and str strings.

**Comment by pkcakeout** [comment]
Jup - this fixes the python2 issue, and should work for python3 as well

**Comment by jmsmkn** [comment]
Importing `from future.moves.urllib.parse import urljoin` solves this too, and keeps futurize happy. Useful to know for when when we do the python 3 upgrade on the rest of the codebase as futurize will prefer to implement conversion using `install_aliases` rather than using `future.moves`. We should always use the latter, check the config to see if we can make this the default. 

I also added a test :-)
